services:
  hebpipe:
    container_name: hebpipe-gpu
    image: hebpipe_image:gpu # Define the image name and tag for GPU
    build:
      context: ..
      dockerfile: docker/Dockerfile.gpu # Use the GPU Dockerfile
      args:
        # Pass Python version as argument
        PY_VERSION: 3
        HEBPIPE_INSTALL_TYPE: gpu
    # Configure GPU runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Optional: Mount a volume to process local files
    volumes:
      # Use environment variables for local path, container path is fixed
      - ${LOCAL_INPUT_DIR}:${CONTAINER_INPUT_DIR}
    # command: ["example_in.txt"] # Example: processes example_in.txt using the ENTRYPOINT 